name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - '**/*.go'
      - 'makefile'
      - 'go.mod'
      - 'go.sum'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    uses: Open-CMSIS-Pack/workflows-and-actions-collection/.github/workflows/build.yml@main
    with:
      program: 'cbridge'
